/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javalin.metrics.example;

import io.javalin.Javalin;
import io.micrometer.core.instrument.Metrics;
import io.micrometer.prometheus.PrometheusConfig;
import io.micrometer.prometheus.PrometheusMeterRegistry;

public class App {
    public static void main(String[] args) {
        Javalin app = Javalin.create()
                .enableDebugLogging()
                .enableMetrics()
                .start(7000);

        final PrometheusMeterRegistry registry = new PrometheusMeterRegistry(PrometheusConfig.DEFAULT);
        Metrics.globalRegistry.add(registry);

        app.get("/prometheus", ctx -> ctx.result(registry.scrape()));
    }
}
